### ISSUE TITLE
Non-static method WP_Feed_Cache::create() 

### ISSUE THREAD

**Issue by wpessential** [reduxframework/redux-framework-4#55] opened 2019-08-06 16:00 UTC
Hi team redux,

I have found an error of Deprecated (Suppressed). The error appears on the WP Dashboard.
Here is the error:

```
Non-static method WP_Feed_Cache::create() should not be called statically
wp_dashboard()
wp-admin/index.php:148
do_meta_boxes()
wp-admin/includes/dashboard.php:235
Redux_Dashboard->redux_dashboard_widget()
wp-admin/includes/template.php:1304
wp_widget_rss_output()
wp-content/plugins/redux-framework/ReduxCore/inc/classes/class-redux-dashboard.php:54
fetch_feed()
wp-includes/widgets.php:1442
SimplePie->init()
wp-includes/feed.php:764
SimplePie_Registry->call()
wp-includes/class-simplepie.php:1313
wp-includes/SimplePie/Registry.php:215
```

And the redux version is **4.0.2**

Regard 
**Themecat_Info**

**Comment by dovy** [comment] 2019-08-06 16:09
This is a widespread issue. Could you test this fix for me to see if it resolves it on your end? I can't reproduce it.

Change: `public function redux_dashboard_widget() {` to `public static function redux_dashboard_widget() {`

As you can see by a simple Google search, this is a widespread issue that, but I'd love to solve it properly.  ;)

https://core.trac.wordpress.org/attachment/ticket/29204/0001-29204-Fix-errors-about-non-static-WP_Feed_Cache-crea.2.patch

If it works, I'll submit the fix. Please let me know.

**Comment by themecatinfo** [comment] 2019-08-06 16:12
> This is a widespread issue. Could you test this fix for me to see if it resolves it on your end? I can't reproduce it.
> 
> Change: `public function redux_dashboard_widget() {` to `public static function redux_dashboard_widget() {`
> 
> As you can see by a simple Google search, this is a widespread issue that, but I'd love to solve it properly. ;)
> 
> https://core.trac.wordpress.org/attachment/ticket/29204/0001-29204-Fix-errors-about-non-static-WP_Feed_Cache-crea.2.patch
> 
> If it works, I'll submit the fix. Please let me know.

Ok, I try :)

**Comment by themecatinfo** [comment] 2019-08-06 17:19
@dovy no success found by

> Change: public function redux_dashboard_widget() { to public static function redux_dashboard_widget() {

**Comment by dovy** [comment] 2019-08-06 17:19
Hmm. I am unsure how to resolve this. It's a common error.

**Comment by themecatinfo** [comment] 2019-08-06 17:25
Hmm...  
ok, you need to try again if found success, then inform me that what is the way. Also, I try again in other ways.

**Comment by dovy** [comment] 2019-08-06 17:26
Please, if you could find a solution you'd be my hero. haha. I can't even reproduce it over here.

**Comment by themecatinfo** [comment] 2019-08-06 17:27
> Please, if you could find a solution you'd be my hero. haha. I can't even reproduce it over here.

:)

**Comment by voldemortensen** [comment] 2019-08-06 17:48
This is a WordPress core issue, it's done for backwards compatibility.

https://core.trac.wordpress.org/browser/trunk/src/wp-includes/SimplePie/Registry.php#L215

The `&call` method uses `call_user_func_array(array($class, 'create'), $parameters);`.

**Comment by voldemortensen** [comment] 2019-08-06 17:58
The fix would be to figure out a different method for this section, as it's what ultimately calls the problem code.

https://github.com/reduxframework/redux-framework-4/blob/master/ReduxCore/inc/classes/class-redux-dashboard.php#L52-L61

**Comment by themecatinfo** [comment] 2019-08-06 20:09
thanks, @voldemortensen for providing the information.

**Comment by themecatinfo** [comment] 2019-08-06 20:21
@dovy 
I have found a plugin. [https://wordpress.org/plugins/dashboard-feed-widget/](url)
When the plugin has activated, the error hide. Need to check this tiny plugin or need to rearrange the code for https://github.com/reduxframework/redux-framework-4/issues/55#issuecomment-518774074 requirements. I also checked the Elementor plugin and the plugin did not generate the error. [http://prntscr.com/op8pck](url)

**Comment by dovy** [comment] 2019-08-06 20:22
So very odd. Keep digging, please. I'd like to make sure no one gets this error.  ;)

**Comment by kprovance** [comment] 2020-05-10 02:32
We've opted to remove the Dashboard Newsfeed feature for Redux 4.  Closing.

**Closed by kprovance** 2020-05-10 02:32 UTC
