### ISSUE TITLE
The Links Color field doesn't work

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework-4#209] opened 2021-04-05 21:47 UTC
#Steps:

- On the demo options page
- Go to Color selection > Link color > Links Color Option
- Select a color
- See in the frontend that this doesn't work

**Comment by mohammedeisa** [comment] 2021-04-06 18:02
The same issue happens on Redux 4.1.24

**Comment by webbudesign** [comment] 2021-05-05 21:28
The same issue reported before;
Duplicate of #206

**Comment by essamamdani** [comment] 2021-05-22 13:35
I check everything from my side...it works fine as you suggest. if it is not working let me know how to reproduce it

**Comment by mohammedeisa** [comment] 2021-05-25 01:02
Here is a video showing the issue:

https://user-images.githubusercontent.com/3139496/119424285-70ce8180-bd05-11eb-9e4e-6455144e83fa.mp4

The hover and active colors work fine. The issue is with the default state of the link (When it's not clicked).

I see that the theme overrides the link color.

**Comment by kprovance** [comment] 2021-05-25 19:55
Fixed in the latest pull request, 4.1.27

**Closed** 2021-06-11 00:20 UTC
