### ISSUE TITLE
Metabox Lite saving issue when Custom Fields visible - WP5 with Gutenberg

### ISSUE THREAD

**Issue by STV11C** [reduxframework/redux-framework-4#24] opened 2019-03-20 11:43 UTC
## Support Hash
https://support.redux.io/?id=7X91%2FP605ikM1%2Bc0E5l6iLSR%2FLZqcW%2B%2Bbu2YIfVOGak8%2FzaOUycs7RhrZGSSUZewtmNGhEfPh%2FnYhV9DGAQ%2BZA%3D%3D

## Steps to reproduce
Add a Metabox Lite radio option. Enable 'Custom Fields' in Page/Post edit view (in WP5 using Gutenberg). Save the MBL option. After save and while on the page still, save the page again. You'll notice because the 'Custom Fields' was visible (which displays the Redux MBL options) they do not update on Save, so if you save again before refreshing the page, then your Redux MBL option will be overwritten by the previous settings.

## Expected Behavior
Custom Fields (if visible) should update the Redux MBL value on Save.

## Actual Behavior
Custom Fields (if visible) does not update the Redux MBL value on Save.

## Any Error Details (PHP/JavaScript)
No errors.

![redux-mbl-issue](https://user-images.githubusercontent.com/5532744/54681852-84985f00-4b61-11e9-8292-5d2f9b44cc9a.png)

**Comment by dovy** [comment] 2019-03-20 12:02
Wow, interesting. Any chance you would be willing to send me your code (I won't keep anything) so I can debug it directly? That would help. dovy@redux.io. Thanks!

**Comment by STV11C** [comment] 2019-03-20 13:31
Hi Dovy, I'll email you my MBL options now. Thanks.

**Comment by STV11C** [comment] 2019-03-22 00:00
Hi Dovy, just touching base about this issue and if you received my email? Thanks!

**Comment by dovy** [comment] 2019-03-22 01:19
I did, and I see what you mean. So the updates do occur in the DB, but they do not save on the "page". The issue is that the data may be varied from sterilized to just a string. It's something I can add as a feature request, but it won't impact anything really. The data still saves. I'm going to add this to a future feature enhancement. Metaboxes has work for a while without this.

Do you have a particular use case as to why this is concerning?

**Comment by STV11C** [comment] 2019-03-22 01:27
Hey Dovy, thanks for getting back to me. The reason it needs to be fixed is that any user (especially non-devs) who has the 'Custom Fields' visible (whether on purpose or by accident) will most probably experience what I did and not know why their options are constantly switching. I was perplexed for weeks about what was going on, and finally worked it out by chance. Cheers

**Comment by dovy** [comment] 2019-03-22 01:28
Yea, I agree it's a feature we could add. I'll put it on the task list. Thank you for giving me what I needed to try it out.

**Comment by STV11C** [comment] 2019-03-22 01:30
Awesome thanks!

**Comment by kprovance** [comment] 2020-05-10 04:20
Metabox Lite has been removed.  Moving to Pro issue tracker for eval.

**Closed by kprovance** 2020-05-10 04:20 UTC
Labels: enhancement
